import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export interface BorderConfig {
  size: Record<string, string>;
  color: Record<string, string>;
}

const defaultBorder: BorderConfig = {
  size: {},

  color: {},
};

const DARK_PREFIX = "dark:";

function generateCSS(border: BorderConfig): string {
  const widthUIVars = Object.entries(border.size)
    .map(([key, value]) => `  --ui-border-width-${key}: ${value};`)
    .join("\n");

  const widthThemeVars = Object.keys(border.size)
    .map((key) => `  --border-width-${key}: var(--ui-border-width-${key});`)
    .join("\n");

  const colorEntries = Object.entries(border.color);

  const lightColors = colorEntries.filter(
    ([key]) => !key.startsWith(DARK_PREFIX),
  );

  const darkColors = colorEntries.filter(([key]) =>
    key.startsWith(DARK_PREFIX),
  );

  const colorThemeVars = lightColors
    .map(([key]) => `  --border-color-${key}: var(--ui-border-color-${key});`)
    .join("\n");

  const lightColorVars = lightColors
    .map(([key, value]) => `  --ui-border-color-${key}: ${value};`)
    .join("\n");

  const darkColorVars = darkColors
    .map(([key, value]) => {
      const colorName = key.slice(DARK_PREFIX.length);

      return `  --ui-border-color-${colorName}: ${value};`;
    })
    .join("\n");

  return `/**
 * Automatically generated file — do not edit manually.
 * Source: border configuration
 * Generated by Syora UI
 */

@theme inline {
${widthThemeVars}
${colorThemeVars}
}

:root {
${widthUIVars}
${lightColorVars}
}

.dark {
${darkColorVars}
}
`;
}

export default function generateBorder(
  border: Partial<BorderConfig> = {},
  outputPath: string,
) {
  const mergedBorder: BorderConfig = {
    size: {
      ...defaultBorder.size,
      ...border.size,
    },

    color: {
      ...defaultBorder.color,
      ...border.color,
    },
  };

  const css = generateCSS(mergedBorder);

  mkdirSync(outputPath, { recursive: true });
  writeFileSync(join(outputPath, "border.css"), css, "utf8");
}
