import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export type ColorConfig = Record<string, string>;

const DARK_PREFIX = "dark:";

const defaultColors: ColorConfig = {};

function generateCSS(colors: ColorConfig): string {
  const entries = Object.entries(colors);

  const lightColors = entries.filter(([key]) => !key.startsWith(DARK_PREFIX));

  const darkColors = entries.filter(([key]) => key.startsWith(DARK_PREFIX));

  const themeVars = lightColors
    .map(([key]) => {
      return `  --color-${key}: var(--ui-color-${key});`;
    })
    .join("\n");

  const lightVars = lightColors
    .map(([key, value]) => {
      return [
        `  --ui-color-${key}: ${value};`,
        `  --ui-color-${key}-inverse: contrast-color(var(--ui-color-${key}));`,
      ].join("\n");
    })
    .join("\n");

  const darkVars = darkColors
    .map(([key, value]) => {
      const colorName = key.slice(DARK_PREFIX.length);

      return [
        `  --ui-color-${colorName}: ${value};`,
        `  --ui-color-${colorName}-inverse: contrast-color(var(--ui-color-${colorName}));`,
      ].join("\n");
    })
    .join("\n");

  return `/**
 * Automatically generated file — do not edit manually.
 * Source: color configuration
 * Generated by Syora UI
 */

@theme inline {
${themeVars}

${lightColors
  .map(([key]) => `  --color-${key}-inverse: var(--ui-color-${key}-inverse);`)
  .join("\n")}
}

:root {
${lightVars}
}

.dark {
${darkVars}
}
`;
}

export default function generateColors(
  colors: ColorConfig = {},
  outputPath: string,
) {
  const mergedColors: ColorConfig = {
    ...defaultColors,
    ...colors,
  };

  const css = generateCSS(mergedColors);

  mkdirSync(outputPath, { recursive: true });
  writeFileSync(join(outputPath, "colors.css"), css, "utf8");
}
