import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export interface GridConfig {
  columns: Record<string, string>;
  rows: Record<string, string>;
}

const defaultGrid: GridConfig = {
  columns: {},

  rows: {},
};

function generateCSS(grid: GridConfig): string {
  const columnsUIVars = Object.entries(grid.columns)
    .map(([key, value]) => `  --ui-grid-columns-${key}: ${value};`)
    .join("\n");

  const columnsThemeVars = Object.keys(grid.columns)
    .map((key) => `  --grid-cols-${key}: var(--ui-grid-columns-${key});`)
    .join("\n");

  const rowsUIVars = Object.entries(grid.rows)
    .map(([key, value]) => `  --ui-grid-rows-${key}: ${value};`)
    .join("\n");

  const rowsThemeVars = Object.keys(grid.rows)
    .map((key) => `  --grid-rows-${key}: var(--ui-grid-rows-${key});`)
    .join("\n");

  return `/**
 * Automatically generated file — do not edit manually.
 * Source: grid configuration
 * Generated by Syora UI
 */

@theme inline {
${columnsThemeVars}
${rowsThemeVars}
}

:root {
${columnsUIVars}
${rowsUIVars}
}
`;
}

export default function generateGrid(
  grid: Partial<GridConfig> = {},
  outputPath: string,
) {
  const mergedGrid: GridConfig = {
    columns: {
      ...defaultGrid.columns,
      ...grid.columns,
    },

    rows: {
      ...defaultGrid.rows,
      ...grid.rows,
    },
  };

  const css = generateCSS(mergedGrid);

  mkdirSync(outputPath, { recursive: true });
  writeFileSync(join(outputPath, "grid.css"), css, "utf8");
}
