import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export interface LayoutConfig {
  container: Record<string, string>;
  breakpoint: Record<string, string>;
}

const defaultLayout: LayoutConfig = {
  container: {},

  breakpoint: {},
};

function generateCSS(layout: LayoutConfig): string {
  const containerUIVars = Object.entries(layout.container)
    .map(([key, value]) => `  --ui-container-${key}: ${value};`)
    .join("\n");

  const containerThemeVars = Object.keys(layout.container)
    .map((key) => `  --container-${key}: var(--ui-container-${key});`)
    .join("\n");

  const breakpointUIVars = Object.entries(layout.breakpoint)
    .map(([key, value]) => `  --ui-breakpoint-${key}: ${value};`)
    .join("\n");

  const breakpointThemeVars = Object.keys(layout.breakpoint)
    .map((key) => `  --breakpoint-${key}: var(--ui-breakpoint-${key});`)
    .join("\n");

  return `/**
 * Automatically generated file — do not edit manually.
 * Source: layout configuration
 * Generated by Syora UI
 */

@theme inline {
${containerThemeVars}
${breakpointThemeVars}
}

:root {
${containerUIVars}
${breakpointUIVars}
}
`;
}

export default function generateLayout(
  layout: Partial<LayoutConfig> = {},
  outputPath: string,
) {
  const mergedLayout: LayoutConfig = {
    container: {
      ...defaultLayout.container,
      ...layout.container,
    },

    breakpoint: {
      ...defaultLayout.breakpoint,
      ...layout.breakpoint,
    },
  };

  const css = generateCSS(mergedLayout);

  mkdirSync(outputPath, { recursive: true });
  writeFileSync(join(outputPath, "layout.css"), css, "utf8");
}
