import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export interface MotionConfig {
  duration: Record<string, string>;
  ease: Record<string, string>;
}

const defaultMotion: MotionConfig = {
  duration: {},

  ease: {},
};

function generateCSS(motion: MotionConfig): string {
  const durationUIVars = Object.entries(motion.duration)
    .map(([key, value]) => `  --ui-duration-${key}: ${value};`)
    .join("\n");

  const durationThemeVars = Object.keys(motion.duration)
    .map((key) => `  --duration-${key}: var(--ui-duration-${key});`)
    .join("\n");

  const easeUIVars = Object.entries(motion.ease)
    .map(([key, value]) => `  --ui-ease-${key}: ${value};`)
    .join("\n");

  const easeThemeVars = Object.keys(motion.ease)
    .map((key) => `  --ease-${key}: var(--ui-ease-${key});`)
    .join("\n");

  return `/**
 * Automatically generated file — do not edit manually.
 * Source: motion configuration
 * Generated by Syora UI
 */

@theme inline {
${durationThemeVars}
${easeThemeVars}
}

:root {
${durationUIVars}
${easeUIVars}
}
`;
}

export default function generateMotion(
  motion: Partial<MotionConfig> = {},
  outputPath: string,
) {
  const mergedMotion: MotionConfig = {
    duration: {
      ...defaultMotion.duration,
      ...motion.duration,
    },

    ease: {
      ...defaultMotion.ease,
      ...motion.ease,
    },
  };

  const css = generateCSS(mergedMotion);

  mkdirSync(outputPath, { recursive: true });
  writeFileSync(join(outputPath, "motion.css"), css, "utf8");
}
