import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export type RadiusConfig = Record<string, string>;

const defaultRadius: RadiusConfig = {};

function generateCSS(radius: RadiusConfig): string {
  const uiVars = Object.entries(radius)
    .map(([key, value]) => `  --ui-radius-${key}: ${value};`)
    .join("\n");

  const themeVars = Object.keys(radius)
    .map((key) => `  --radius-${key}: var(--ui-radius-${key});`)
    .join("\n");

  return `/**
 * Automatically generated file — do not edit manually.
 * Source: radius configuration
 * Generated by Syora UI
 */

@theme inline {
${themeVars}
}

:root {
${uiVars}
}
`;
}

export default function generateRadius(
  spacing: RadiusConfig = {},
  outputPath: string,
) {
  const mergedRadius: RadiusConfig = {
    ...defaultRadius,
    ...spacing,
  };

  const css = generateCSS(mergedRadius);

  mkdirSync(outputPath, { recursive: true });
  writeFileSync(join(outputPath, "radius.css"), css, "utf8");
}
