import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export type ShadowsConfig = Record<string, string>;

const defaultShadows: ShadowsConfig = {};

function generateCSS(shadows: ShadowsConfig): string {
  const uiVars = Object.entries(shadows)
    .map(([key, value]) => `  --ui-shadow-${key}: ${value};`)
    .join("\n");

  const themeVars = Object.keys(shadows)
    .map((key) => `  --shadow-${key}: var(--ui-shadow-${key});`)
    .join("\n");

  return `/**
 * Automatically generated file — do not edit manually.
 * Source: shadows configuration
 * Generated by Syora UI
 */

@theme inline {
${themeVars}
}

:root {
${uiVars}
}
`;
}

export default function generateShadows(
  shadows: ShadowsConfig = {},
  outputPath: string,
) {
  const mergedShadows: ShadowsConfig = {
    ...defaultShadows,
    ...shadows,
  };

  const css = generateCSS(mergedShadows);

  mkdirSync(outputPath, { recursive: true });
  writeFileSync(join(outputPath, "shadows.css"), css, "utf8");
}
