import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export type SpacingConfig = Record<string, string>;

const defaultSpacing: SpacingConfig = {};

function generateCSS(spacing: SpacingConfig): string {
  const uiVars = Object.entries(spacing)
    .map(([key, value]) => `  --ui-spacing-${key}: ${value};`)
    .join("\n");

  const themeVars = Object.keys(spacing)
    .map((key) => `  --spacing-${key}: var(--ui-spacing-${key});`)
    .join("\n");

  return `/**
 * Automatically generated file — do not edit manually.
 * Source: spacing configuration
 * Generated by Syora UI
 */

@theme inline {
${themeVars}
}

:root {
${uiVars}
}
`;
}

export default function generateSpacing(
  spacing: SpacingConfig = {},
  outputPath: string,
) {
  const mergedSpacing: SpacingConfig = {
    ...defaultSpacing,
    ...spacing,
  };

  const css = generateCSS(mergedSpacing);

  mkdirSync(outputPath, { recursive: true });
  writeFileSync(join(outputPath, "spacing.css"), css, "utf8");
}
