import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export type TypographyConfig = Record<string, string>;

const defaultTypography: TypographyConfig = {};

const BREAKPOINT_PREFIX = /^([^:]+):(.+)$/;

function generateCSS(typography: TypographyConfig): string {
  const entries = Object.entries(typography);

  const baseEntries = entries.filter(([key]) => !BREAKPOINT_PREFIX.test(key));

  const responsiveEntries = entries
    .filter(([key]) => BREAKPOINT_PREFIX.test(key))
    .map(([key, value]) => {
      const [, breakpoint, token] = key.match(BREAKPOINT_PREFIX)!;

      return {
        breakpoint,
        token,
        value,
      };
    });

  const themeVars = baseEntries
    .map(([key]) => `  --text-${key}: var(--ui-text-${key});`)
    .join("\n");

  const baseVars = baseEntries
    .map(([key, value]) => `  --ui-text-${key}: ${value};`)
    .join("\n");

  const responsiveVars = responsiveEntries
    .reduce((groups, entry) => {
      const group = groups.get(entry.breakpoint) ?? [];

      group.push(entry);

      groups.set(entry.breakpoint, group);

      return groups;
    }, new Map<string, typeof responsiveEntries>())
    .entries();

  const mediaQueries = Array.from(responsiveVars)
    .map(([breakpoint, values]) => {
      const variables = values
        .map(({ token, value }) => `    --ui-text-${token}: ${value};`)
        .join("\n");

      return `@media (width >= theme(--breakpoint-${breakpoint})) {
  :root {
${variables}
  }
}`;
    })
    .join("\n\n");

  return `/**
 * Automatically generated file — do not edit manually.
 * Source: typography configuration
 * Generated by Syora UI
 */

@theme inline {
${themeVars}
}

:root {
${baseVars}
}

${mediaQueries}
`;
}

export default function generateTypography(
  typography: TypographyConfig = {},
  outputPath: string,
) {
  const mergedTypography: TypographyConfig = {
    ...defaultTypography,
    ...typography,
  };

  const css = generateCSS(mergedTypography);

  mkdirSync(outputPath, { recursive: true });
  writeFileSync(join(outputPath, "typography.css"), css, "utf8");
}
