import { parse } from "@babel/parser";
import traverse from "@babel/traverse";
import MagicString from "magic-string";
import { createUnplugin } from "unplugin";
import { loadEnv, type ResolvedConfig } from "vite";
import { join, relative, resolve } from "node:path";
import {
  atomicWriteFile,
  loadRuntimeEnv,
  normalizeDir,
  type LoadEnvResult,
} from "@/utils/index.js";
import merge from "lodash/merge.js";
import { useConfig } from "@/config/index.js";

interface SyoraEnvPluginOptions {
  output?: string;
}

const VIRTUAL_ID = ":runtime";
const RESOLVED_VIRTUAL_ID = "\:runtime";

/**
 * Generates the `.d.ts` content describing the shape of the environment
 * variables exposed by this plugin:
 * - `*_PUBLIC_*` variables are grouped under `public`
 * - the rest (server-only) are declared directly on the interface
 * - all names are converted to camelCase, prefix stripped
 */
function generateDts(envs: LoadEnvResult["types"], output: string) {
  const publicKeys: [string, string][] = [];
  const privateKeys: [string, string][] = [];

  Object.keys(envs.public).forEach((key) => {
    publicKeys.push([key, envs.public[key]!]);
  });

  Object.keys(envs.private).forEach((key) => {
    privateKeys.push([key, envs.private[key]!]);
  });

  const publicLines = publicKeys
    .map(([key, value]) => `    ${key}: ${value};`)
    .join("\n");

  const privateLines = privateKeys
    .map(([key, value]) => `  ${key}: ${value};`)
    .join("\n");

  const code = `/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck

interface RuntimeEnv {
  public: {
${publicLines || "    // no public variables"}
    [key:string]: unknown
  }

${privateLines || "  // no private variables (server-only)"}
  [key:string]: unknown
}

declare module '${normalizeDir(relative(output, resolve(import.meta.dirname, "types.js")))}' {
  interface RuntimeValues extends RuntimeEnv {}
}

export {};
`;

  const dtsPath = join(output, "runtime.d.ts");
  atomicWriteFile(dtsPath, code);
}

/**
 * @fileoverview Vite plugin that exposes custom environment variables on
 * `import.meta.env`.
 *
 * Only environment variables prefixed with `SYO_` or `SYORA_` are picked up;
 * everything else is ignored (mirrors Vite's own `VITE_` convention).
 *
 * Visibility rules:
 * - `SYO_PUBLIC_*` / `SYORA_PUBLIC_*` / `VITE_PUBLIC_*` -> exposed on both the client bundle
 *   and the server (SSR) bundle.
 * - Any other `SYO_*` / `SYORA_*` / `VITE_*` variable -> exposed **server-side only**.
 *   References to these variables in client code are left untouched and
 *   simply resolve to `undefined` at runtime, preventing secrets from
 *   leaking into the client bundle.
 *
 * A `.d.ts` is also written on every `configResolved`, describing the shape
 * `{ public: { ... }, ...private }` of the detected SYO_/SYORA_/VITE_
 * variables, for autocompletion.
 *
 * @example
 * ```ts
 * // .env
 * // SYO_PUBLIC_API_URL=https://api.example.com
 * // SYO_DATABASE_URL=postgres://...
 *
 * console.log(import.meta.env.SYO_PUBLIC_API_URL); // available everywhere
 * console.log(import.meta.env.SYO_DATABASE_URL);   // available server-side only
 * ```
 *
 * @remarks
 * Values are statically replaced at transform time (the same mechanism Vite
 * uses natively for `VITE_`-prefixed variables), so unused references are
 * tree-shaken and no secret ends up embedded in client code unless it was
 * explicitly marked `PUBLIC`.
 */
export default createUnplugin((options: SyoraEnvPluginOptions = {}) => {
  const { output = process.cwd() } = options;

  // Populated once in `configResolved`, then reused for every transform call.
  let envs: LoadEnvResult;

  return {
    name: "syora:runtime",
    enforce: "post",

    vite: {
      /**
       * Loads every `.env*` file (merged with `process.env`) for the
       * current mode, then splits the relevant SYO_/SYORA_ variables into
       * two lookup maps: one for server-side usage (all of them) and one
       * for client-side usage (public ones only). Also (re)writes the
       * `.d.ts` describing their shape.
       */
      configResolved(config: ResolvedConfig) {
        // Passing an empty string as the third argument disables Vite's
        // default `VITE_`-only prefix filtering, so we get every variable
        // and apply our own filtering below.

        const rawEnv = loadEnv(config.mode, config.root, "");
        envs = loadRuntimeEnv({ envs: rawEnv });

        generateDts(envs.types, output);
      },

      resolveId(id) {
        if (id === VIRTUAL_ID) return RESOLVED_VIRTUAL_ID;
      },

      /**
       * Serves `virtual:syora-runtime`: a plain object matching the
       * `{ public: {...}, ...private }` shape, populated with the values
       * scoped for this build target (client -> public only, server ->
       * everything). This is the runtime counterpart of the `.d.ts`
       * generated by `generateDts`.
       */
      load(id, options) {
        if (id !== RESOLVED_VIRTUAL_ID) return;

        const runtime = useConfig()._runtime;

        const scopedRuntime = options?.ssr
          ? runtime
          : { public: runtime.public };

        const scopedEnv = options?.ssr
          ? merge(envs.runtime.private, { public: envs.runtime.public })
          : { public: envs.runtime.public };

        return `export const values = ${JSON.stringify(merge(scopedRuntime, scopedEnv))} `;
      },

      transform(code, id, options) {
        // Only target JS/TS/JSX/TSX files. (.vue files reach this point
        // already compiled to JS by @vitejs/plugin-vue, provided that
        // plugin is registered before this one.)
        if (!/\.(vue|[jt]sx?)(\?|$)/.test(id)) return;

        // Cheap early exit before paying for a full AST parse.
        if (
          !code.includes("import.meta.env.SYO_") &&
          !code.includes("import.meta.env.SYORA_")
        ) {
          return;
        }

        let ast;
        try {
          ast = parse(code, {
            sourceType: "module",
            plugins: ["typescript", "jsx"],
          });
        } catch {
          // Content is not parseable as-is (e.g. a raw, uncompiled SFC) -> skip it
          return;
        }

        // Pick the correct visibility scope depending on whether this
        // module is being compiled for the server (SSR) or the client.
        const scopedEnv = options?.ssr
          ? merge(envs.raw.public, envs.raw.private)
          : envs.raw.public;

        const s = new MagicString(code);
        let touched = false;

        traverse(ast, {
          MemberExpression(path) {
            const { object, property } = path.node;

            // Match only the exact pattern `import.meta.env.<identifier>`
            if (
              property.type !== "Identifier" ||
              object.type !== "MemberExpression" ||
              object.property.type !== "Identifier" ||
              object.property.name !== "env" ||
              object.object.type !== "MetaProperty" ||
              object.object.meta.name !== "import" ||
              object.object.property.name !== "meta"
            ) {
              return;
            }

            const value = scopedEnv[property.name];

            // Unknown or out-of-scope variable (e.g. a private var accessed
            // from client code): leave it untouched so it naturally
            // resolves to `undefined` at runtime instead of leaking data.
            if (value === undefined) return;

            s.overwrite(path.node.start!, path.node.end!, value);
            touched = true;
          },
        });

        if (!touched) return;

        return {
          code: s.toString(),
          map: s.generateMap({ hires: true, source: id }),
        };
      },
    },
  };
});
