import { readFile } from "node:fs/promises";
import { join, relative, resolve } from "node:path";

import {
  atomicWriteFile,
  defineModule,
} from "../../../packages/core/src/index.js";
import type {
  I18nConfig,
  I18nMessage,
  I18nMessageObject,
} from "./types/index.js";

const LOCALES_DIRECTORY = "i18n/locales";
const GENERATED_TYPES_FILE = "i18n/types.d.ts";

function generateLocaleTypes(
  options: I18nConfig,
  messages: I18nMessageObject,
  output: string,
): void {
  const configuredLocales = (options.locales ?? []).map(
    (locale) => locale.code,
  );
  const localeCodes = [
    ...new Set(
      configuredLocales.length ? configuredLocales : Object.keys(messages),
    ),
  ];
  const localeType = localeCodes.length
    ? localeCodes.map((locale) => JSON.stringify(locale)).join(" | ")
    : "never";

  const declaration = `/* eslint-disable */
/* prettier-ignore */
// Generated by the Syora i18n module. Do not edit manually.

declare module '@intlify/core-base' {
  interface GeneratedTypeConfig {
    locale: ${localeType}
  }
}

export {};
`;

  atomicWriteFile(join(output, GENERATED_TYPES_FILE), declaration);
}

async function loadLocaleMessages(
  options: I18nConfig,
): Promise<I18nMessageObject> {
  const root = process.cwd();
  const localesDirectory = resolve(root, LOCALES_DIRECTORY);
  const messages: I18nMessageObject = {};

  await Promise.all(
    (options.locales ?? []).map(async (locale) => {
      const filePath = resolve(localesDirectory, locale.file);
      const relativePath = relative(localesDirectory, filePath);

      if (relativePath.startsWith("..") || relativePath.startsWith("/")) {
        throw new Error(
          `[i18n] Locale file "${locale.file}" must stay inside "${LOCALES_DIRECTORY}".`,
        );
      }

      let content: string;
      try {
        content = await readFile(filePath, "utf8");
      } catch (error) {
        throw new Error(
          `[i18n] Cannot read locale "${locale.code}" from "${filePath}".`,
          { cause: error },
        );
      }

      try {
        messages[locale.code] = JSON.parse(content) as I18nMessage;
      } catch (error) {
        throw new Error(
          `[i18n] Locale file "${filePath}" contains invalid JSON.`,
          { cause: error },
        );
      }
    }),
  );

  return { ...messages, ...options.messages };
}

export default defineModule<I18nConfig>({
  meta: { name: "i18n" },

  configKey: "i18n",

  async setup(options, config) {
    const messages = await loadLocaleMessages(options);
    generateLocaleTypes(options, messages, config.output);

    return {
      _runtime: {
        public: {
          i18n: { ...options, messages },
        },
      },
    };
  },
});
