import fs from "node:fs";
import path from "node:path";
import type { ComponentInfo } from "./types";
import { atomicWriteFile } from "@/utils";

/**
 * Generates a `components.d.ts` declaration file for the locally scanned
 * components (components resolved via `resolvers` are not included, since
 * they are only resolved lazily while transforming each file).
 */
export function generateDts(
  root: string,
  map: Map<string, ComponentInfo>,
  target: string | boolean,
): void {
  root = typeof target === "string" ? path.dirname(target) : root;

  const filePath = path.resolve(
    root,
    typeof target === "string" ? target : "components.d.ts",
  );
  const entries = [...map.entries()]
    .filter(([, info]) => path.isAbsolute(info.from))
    .sort(([a], [b]) => a.localeCompare(b));

  const lines = entries.map(([name, info]) => {
    const rel = `./${path.relative(root, info.from).replace(/\\/g, "/")}`;
    return `    ${name}: typeof import('${rel}')['default']`;
  });

  const content = `/* eslint-disable */
// Auto-generated by unplugin-vue-components-rename.
// Do not edit by hand: this file is regenerated on every component scan.
export {}

declare module 'vue' {
  export interface GlobalComponents {
${lines.join("\n")}
  }
}
`;

  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

  atomicWriteFile(filePath, content);
}
