import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, isAbsolute, relative, resolve } from "node:path";
import type { ComponentInfo } from "./types";
import { slash } from "./utils";

const HEADER = `/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by syora:components
// Do not edit this file manually — it will be overwritten.
export {}

declare module 'vue' {
  export interface GlobalComponents {
`;

const FOOTER = `  }
}
`;

export function renderDts(
  components: Map<string, ComponentInfo>,
  dtsFilePath: string,
): string {
  const dtsDir = dirname(dtsFilePath);
  const names = [...components.keys()].sort((a, b) => a.localeCompare(b));

  const lines = names.map((name) => {
    const info = components.get(name)!;
    let importPath = slash(relative(dtsDir, info.path));
    if (!importPath.startsWith(".")) importPath = `./${importPath}`;
    return `    ${name}: typeof import('${importPath}')['default']`;
  });

  return `${HEADER}${lines.join("\n")}\n${FOOTER}`;
}

/** Writes the declaration file, skipping the write if content is unchanged (avoids HMR churn). */
export async function writeDts(
  components: Map<string, ComponentInfo>,
  dts: string | false,
  root: string,
): Promise<void> {
  if (!dts) return;

  const dtsFilePath = isAbsolute(dts) ? dts : resolve(root, dts);
  const content = renderDts(components, dtsFilePath);

  try {
    const existing = await readFile(dtsFilePath, "utf-8");
    if (existing === content) return;
  } catch {
    // File doesn't exist yet — it will be created below.
  }

  await mkdir(dirname(dtsFilePath), { recursive: true });
  await writeFile(dtsFilePath, content, "utf-8");
}
